### ISSUE TITLE
Problem on loading data

### ISSUE THREAD

**Issue by Zhixuan-Jing** [JSB-UCLA/scReadSim#1]
When I have all paths set and ready to run the code, it crushed and I noticed that the path is incorrect. I think it is the problem of path setting in the function CreateFeatureSets. The screenshot is atatched below.
<img width="891" alt="1678769235569" src="https://user-images.githubusercontent.com/57510261/224896556-9f2e15c1-d8e0-49bb-abe9-552a57749783.png">

**Comment by Dominic7227** [comment]
Thanks for your feedback, Zhixuan! Could you please show me how you specified your BAM file's path when you run CreateFeatureSets? It seems to me that you somehow concatenated the scReadSim package resources' path and your bam file path. My quick suggestion is to specify the absolute path of your BAM file for the argument 'INPUT_bamfile'.

**Comment by Zhixuan-Jing** [comment]
After checking it I run the code again, and the problem is the same. Like the screenshot shown below, which contains my file directory, the file path is still not correct.
<img width="1280" alt="1678774420577" src="https://user-images.githubusercontent.com/57510261/224912272-cff59949-92cf-4ec8-b560-4dd21f98bc63.png">

**Comment by Dominic7227** [comment]
Thanks for posting your script here, and that helps! It shows that you are using function `pkg_resources.resource_filename` to specify the paths for your files. Well, you shouldn't use this function if you are using your own file, because `pkg_resources.resource_filename` essentially returns the package installation path (check its documentation here: https://setuptools.pypa.io/en/latest/pkg_resources.html). That's why python can not find your BAM file since it concatenates the package installation path and your own BAM file path. The reason I used it in the tutorial is that I need to load the demo data stored along with the package. 

**Solution: directly specify the paths for your own data like** 
```
INPUT_bamfile = "your_path_to_bamfile/name.bam"
```
and in your case, you should use `INPUT_bamfile = data_dir + "%s.bam" % filename`.

**Comment by Zhixuan-Jing** [comment]
Problem solved. Thanks for your help.
